services:
  - type: web
    name: bytebot-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: bytebot
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
      - key: FRONTEND_ORIGINS
        value: https://chatbot-ui-git-main-gentlederr099.vercel.app,https://chatbot-ui-puce-psi-27.vercel.app,http://127.0.0.1:8028,http://localhost:8028,null
